# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS iap::iap iap::odometry_estimation_ct iap::odometry_estimation_cpu iap::sub_mapping iap::sub_mapping_passthrough iap::global_mapping iap::global_mapping_pose_graph iap::odometry_estimation_gpu iap::standard_viewer iap::interactive_viewer iap::memory_monitor iap::map_editor)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target iap::iap
add_library(iap::iap SHARED IMPORTED)

set_target_properties(iap::iap PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLIM_USE_OPENCV"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/iap;/usr/include/opencv4"
  INTERFACE_LINK_LIBRARIES "Boost::boost;Boost::serialization;Eigen3::Eigen;gtsam;gtsam_points::gtsam_points;OpenMP::OpenMP_CXX;spdlog::spdlog;\$<TARGET_NAME_IF_EXISTS:Iridescence::Iridescence>;opencv_core"
)

# Create imported target iap::odometry_estimation_ct
add_library(iap::odometry_estimation_ct SHARED IMPORTED)

set_target_properties(iap::odometry_estimation_ct PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::odometry_estimation_cpu
add_library(iap::odometry_estimation_cpu SHARED IMPORTED)

set_target_properties(iap::odometry_estimation_cpu PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::sub_mapping
add_library(iap::sub_mapping SHARED IMPORTED)

set_target_properties(iap::sub_mapping PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::sub_mapping_passthrough
add_library(iap::sub_mapping_passthrough SHARED IMPORTED)

set_target_properties(iap::sub_mapping_passthrough PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::global_mapping
add_library(iap::global_mapping SHARED IMPORTED)

set_target_properties(iap::global_mapping PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::global_mapping_pose_graph
add_library(iap::global_mapping_pose_graph SHARED IMPORTED)

set_target_properties(iap::global_mapping_pose_graph PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::odometry_estimation_gpu
add_library(iap::odometry_estimation_gpu SHARED IMPORTED)

set_target_properties(iap::odometry_estimation_gpu PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::standard_viewer
add_library(iap::standard_viewer SHARED IMPORTED)

set_target_properties(iap::standard_viewer PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::interactive_viewer
add_library(iap::interactive_viewer SHARED IMPORTED)

set_target_properties(iap::interactive_viewer PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::memory_monitor
add_library(iap::memory_monitor SHARED IMPORTED)

set_target_properties(iap::memory_monitor PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

# Create imported target iap::map_editor
add_library(iap::map_editor SHARED IMPORTED)

set_target_properties(iap::map_editor PROPERTIES
  INTERFACE_LINK_LIBRARIES "iap::iap"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/iap-targetsExport-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
