#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate an IEEE Trans-style methodology chapter skeleton from docs/TRACEABILITY.md

Usage:
  python3 tools/methodology/gen_methodology.py \
    --trace docs/TRACEABILITY.md \
    --template tools/methodology/methodology_template.tex \
    --out docs/methodology/methodology.tex
"""

import argparse
import os
import re
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Optional


@dataclass
class TraceRow:
    req_id: str
    desc: str
    impl: str
    test: str
    logs: str
    status: str


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def sh(cmd: List[str], cwd: Path) -> str:
    try:
        return subprocess.check_output(cmd, cwd=cwd).decode().strip()
    except Exception:
        return ""


def get_git_meta(root: Path) -> str:
    sha = sh(["git", "rev-parse", "--short", "HEAD"], root)
    branch = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], root)
    dirty = sh(["git", "status", "--porcelain"], root)
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    dirty_flag = "dirty" if dirty else "clean"
    parts = [f"time={stamp}", f"branch={branch or 'n/a'}", f"sha={sha or 'n/a'}", f"state={dirty_flag}"]
    return " | ".join(parts)


def parse_traceability_md(md_path: Path) -> List[TraceRow]:
    """
    Parse a markdown table with header containing 'Req ID' and typical columns.
    We expect rows like:
    | IAP-RQ-001 | desc | ... | impl | test | logs | status |
    """
    text = md_path.read_text(encoding="utf-8", errors="ignore").splitlines()

    # Find table header
    header_idx = None
    for i, line in enumerate(text):
        if line.strip().startswith("|") and "Req ID" in line and "Implementation" in line:
            header_idx = i
            break
    if header_idx is None:
        return []

    # Next line is separator like |---|---|
    rows = []
    for line in text[header_idx + 2 :]:
        if not line.strip().startswith("|"):
            # stop when leaving the table block
            if rows:
                break
            else:
                continue

        # split by '|' while trimming
        parts = [p.strip() for p in line.strip().strip("|").split("|")]
        # We support both your earlier TRACEABILITY format and slight variations.
        # Minimal needed fields:
        if len(parts) < 7:
            continue

        req_id = parts[0]
        desc = parts[1]
        impl = parts[3]
        test = parts[4]
        logs = parts[5]
        status = parts[6]

        if not req_id.startswith("IAP-RQ-"):
            continue

        rows.append(TraceRow(req_id=req_id, desc=desc, impl=impl, test=test, logs=logs, status=status))

    return rows


def latex_escape(s: str) -> str:
    # minimal escaping for table text
    repl = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = ""
    for ch in s:
        out += repl.get(ch, ch)
    return out


def make_trace_table(rows: List[TraceRow]) -> str:
    if not rows:
        return r"\emph{No traceability rows found. Please maintain docs/TRACEABILITY.md.}"

    # keep it compact: show Req, impl, logs, status
    lines = []
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Requirement-to-implementation traceability summary.}")
    lines.append(r"\label{tab:traceability}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{p{0.16\linewidth} p{0.44\linewidth} p{0.26\linewidth} p{0.08\linewidth}}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Req} & \textbf{Implementation} & \textbf{Logs/Metrics} & \textbf{Status} \\")
    lines.append(r"\hline")

    for r in rows:
        req = latex_escape(r.req_id)
        impl = latex_escape(r.impl)
        logs = latex_escape(r.logs)
        status = latex_escape(r.status)
        lines.append(f"{req} & {impl} & {logs} & {status} \\\\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def inject_meta_comment(tex: str, meta: str) -> str:
    comment = f"% GENERATED BY gen_methodology.py ({meta})\n"
    if tex.startswith("% GENERATED"):
        # replace first line block if already exists
        tex = re.sub(r"^% GENERATED.*\n", comment, tex, flags=re.MULTILINE)
        return tex
    return comment + tex


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trace", required=True, help="Path to docs/TRACEABILITY.md")
    ap.add_argument("--template", required=True, help="Path to methodology_template.tex")
    ap.add_argument("--out", required=True, help="Output path, e.g., docs/methodology/methodology.tex")
    args = ap.parse_args()

    root = repo_root()
    trace_path = (root / args.trace).resolve()
    tpl_path = (root / args.template).resolve()
    out_path = (root / args.out).resolve()

    if not trace_path.exists():
        raise FileNotFoundError(f"TRACEABILITY not found: {trace_path}")
    if not tpl_path.exists():
        raise FileNotFoundError(f"Template not found: {tpl_path}")

    rows = parse_traceability_md(trace_path)
    table_tex = make_trace_table(rows)

    tpl = tpl_path.read_text(encoding="utf-8", errors="ignore")
    tex = tpl.replace("{{TRACEABILITY_TABLE}}", table_tex)

    meta = get_git_meta(root)
    tex = inject_meta_comment(tex, meta)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex, encoding="utf-8")
    print(f"[ok] generated: {out_path}")
    print(f"[info] rows: {len(rows)}")


if __name__ == "__main__":
    main()