import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.actions import GroupAction
from launch.actions import IncludeLaunchDescription
from launch.actions import LogInfo
from launch.actions import OpaqueFunction
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _as_bool(value):
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def _launch_setup(context):
    iap_share = get_package_share_directory("iap")
    phase2_map_topic = "/map_generator/global_cloud"
    use_iap_odom = _as_bool(LaunchConfiguration("use_iap_odom_for_planner").perform(context))
    planner_odom_topic = "/drone_0_visual_slam/odom" if use_iap_odom else "/sim/drone_0/truth_odom"
    goal_x = LaunchConfiguration("goal_x").perform(context)
    goal_y = LaunchConfiguration("goal_y").perform(context)
    goal_z = LaunchConfiguration("goal_z").perform(context)
    point_num = LaunchConfiguration("point_num").perform(context)

    demo9_args = {
        "start_rviz": "false",
        "use_gnss": LaunchConfiguration("use_gnss"),
        "use_araim": LaunchConfiguration("use_araim"),
        "use_iap_odom_for_planner": LaunchConfiguration("use_iap_odom_for_planner"),
        "goal_x": goal_x,
        "goal_y": goal_y,
        "goal_z": goal_z,
        "point_num": point_num,
        "point1_x": LaunchConfiguration("point1_x"),
        "point1_y": LaunchConfiguration("point1_y"),
        "point1_z": LaunchConfiguration("point1_z"),
        "point2_x": LaunchConfiguration("point2_x"),
        "point2_y": LaunchConfiguration("point2_y"),
        "point2_z": LaunchConfiguration("point2_z"),
        "point3_x": LaunchConfiguration("point3_x"),
        "point3_y": LaunchConfiguration("point3_y"),
        "point3_z": LaunchConfiguration("point3_z"),
        "point4_x": LaunchConfiguration("point4_x"),
        "point4_y": LaunchConfiguration("point4_y"),
        "point4_z": LaunchConfiguration("point4_z"),
        "point5_x": LaunchConfiguration("point5_x"),
        "point5_y": LaunchConfiguration("point5_y"),
        "point5_z": LaunchConfiguration("point5_z"),
        "point6_x": LaunchConfiguration("point6_x"),
        "point6_y": LaunchConfiguration("point6_y"),
        "point6_z": LaunchConfiguration("point6_z"),
        "run_duration_s": LaunchConfiguration("run_duration_s"),
        "use_so3_dynamics": LaunchConfiguration("use_so3_dynamics"),
        "planner_use_dynamic": LaunchConfiguration("planner_use_dynamic"),
        "use_dynamic_obstacles": LaunchConfiguration("use_dynamic_obstacles"),
        "map_source": LaunchConfiguration("map_source"),
        "map_generator_mode": "off",
        "allow_truth_alignment": LaunchConfiguration("allow_truth_alignment"),
        "log_phase1": LaunchConfiguration("log_phase1"),
        "enable_truth_araim_compare": LaunchConfiguration("enable_truth_araim_compare"),
        "truth_araim_compare_csv_name": LaunchConfiguration("truth_araim_compare_csv_name"),
        "gnss_ephemeris_source": LaunchConfiguration("gnss_ephemeris_source"),
        "gnss_enabled_constellations": LaunchConfiguration("gnss_enabled_constellations"),
        "gnss_scenario_file": LaunchConfiguration("gnss_scenario_file"),
        "gnss_rinex_nav_file": LaunchConfiguration("gnss_rinex_nav_file"),
        "gnss_rinex_ephem_max_age_s": LaunchConfiguration("gnss_rinex_ephem_max_age_s"),
        "gnss_fallback_to_synthetic_on_rinex_error": LaunchConfiguration(
            "gnss_fallback_to_synthetic_on_rinex_error"
        ),
        "gnss_enable_map_occlusion": LaunchConfiguration("gnss_enable_map_occlusion"),
        "gnss_enable_skymask": LaunchConfiguration("gnss_enable_skymask"),
        "gnss_enable_nlos": LaunchConfiguration("gnss_enable_nlos"),
        "gnss_enable_multipath": LaunchConfiguration("gnss_enable_multipath"),
        "gnss_enable_fault_injection": LaunchConfiguration("gnss_enable_fault_injection"),
        "gnss_sky_dome_follow_receiver": LaunchConfiguration("gnss_sky_dome_follow_receiver"),
        "gnss_sky_dome_center_x": LaunchConfiguration("gnss_sky_dome_center_x"),
        "gnss_sky_dome_center_y": LaunchConfiguration("gnss_sky_dome_center_y"),
        "gnss_sky_dome_center_z": LaunchConfiguration("gnss_sky_dome_center_z"),
        "drone_id": LaunchConfiguration("drone_id"),
        "init_x": LaunchConfiguration("init_x"),
        "init_y": LaunchConfiguration("init_y"),
        "init_z": LaunchConfiguration("init_z"),
        "map_size_x": LaunchConfiguration("map_size_x"),
        "map_size_y": LaunchConfiguration("map_size_y"),
        "map_size_z": LaunchConfiguration("map_size_z"),
        "planner_use_integrity_cost": LaunchConfiguration("planner_use_integrity_cost"),
        "planner_lambda_integrity": LaunchConfiguration("planner_lambda_integrity"),
        "planner_integrity_field_stale_timeout_s": LaunchConfiguration(
            "planner_integrity_field_stale_timeout_s"
        ),
        "planner_integrity_nearest_radius_m": LaunchConfiguration(
            "planner_integrity_nearest_radius_m"
        ),
        "planner_integrity_cost_max": LaunchConfiguration("planner_integrity_cost_max"),
        "planner_integrity_grad_norm_max": LaunchConfiguration("planner_integrity_grad_norm_max"),
    }

    return [
        LogInfo(msg="[demo11] 20m x 20m random forest scenario with sparse canopies"),
        LogInfo(
            msg=(
                f"[demo11] planner goal argument resolved to "
                f"({goal_x}, {goal_y}, {goal_z}), point_num={point_num}"
            )
        ),
        Node(
            package="iap",
            executable="demo11_corridor_map_publisher",
            name="demo11_corridor_map_publisher",
            output="screen",
            parameters=[
                {"resolution_m": float(LaunchConfiguration("corridor_map_resolution_m").perform(context))},
                {"publish_rate_hz": float(LaunchConfiguration("corridor_map_publish_rate_hz").perform(context))},
                {"frame_id": "map"},
                {"forest_size_x_m": float(LaunchConfiguration("forest_size_x_m").perform(context))},
                {"forest_size_y_m": float(LaunchConfiguration("forest_size_y_m").perform(context))},
                {"tree_density_lower_left_per_m2": float(LaunchConfiguration("tree_density_lower_left_per_m2").perform(context))},
                {"tree_density_lower_right_per_m2": float(LaunchConfiguration("tree_density_lower_right_per_m2").perform(context))},
                {"tree_density_upper_left_per_m2": float(LaunchConfiguration("tree_density_upper_left_per_m2").perform(context))},
                {"tree_density_upper_right_per_m2": float(LaunchConfiguration("tree_density_upper_right_per_m2").perform(context))},
                {"stratified_cell_size_m": float(LaunchConfiguration("stratified_cell_size_m").perform(context))},
                {"canopy_density_lower_left": float(LaunchConfiguration("canopy_density_lower_left").perform(context))},
                {"canopy_density_lower_right": float(LaunchConfiguration("canopy_density_lower_right").perform(context))},
                {"canopy_density_upper_left": float(LaunchConfiguration("canopy_density_upper_left").perform(context))},
                {"canopy_density_upper_right": float(LaunchConfiguration("canopy_density_upper_right").perform(context))},
                {"canopy_hemisphere_radius_min_m": float(LaunchConfiguration("canopy_hemisphere_radius_min_m").perform(context))},
                {"canopy_hemisphere_radius_max_m": float(LaunchConfiguration("canopy_hemisphere_radius_max_m").perform(context))},
                {"canopy_leaf_ball_radius_m": float(LaunchConfiguration("canopy_leaf_ball_radius_m").perform(context))},
                {"canopy_ball_spacing_ratio": float(LaunchConfiguration("canopy_ball_spacing_ratio").perform(context))},
                {"canopy_resolution_m": float(LaunchConfiguration("canopy_resolution_m").perform(context))},
                {"random_seed": int(LaunchConfiguration("forest_random_seed").perform(context))},
                {"trunk_radius_m": float(LaunchConfiguration("trunk_radius_m").perform(context))},
                {"trunk_min_height_m": float(LaunchConfiguration("trunk_min_height_m").perform(context))},
                {"trunk_max_height_m": float(LaunchConfiguration("trunk_max_height_m").perform(context))},
            ],
        ),
        GroupAction(
            scoped=True,
            actions=[
                IncludeLaunchDescription(
                    PythonLaunchDescriptionSource(
                        os.path.join(iap_share, "launch", "demo9_ego_planner_closed_loop.launch.py")
                    ),
                    launch_arguments=demo9_args.items(),
                ),
            ],
        ),
        Node(
            package="iap",
            executable="phase2_planner_integrity_evaluator",
            name="phase2_planner_integrity_evaluator",
            output="screen",
            parameters=[
                {"log_root": "/home/dev/ws_iap/src/iap/log"},
                {"odom_topic": planner_odom_topic},
                {"bspline_topic": "/drone_0_planning/bspline"},
                {"pos_cmd_topic": "/drone_0_planning/pos_cmd"},
                {"map_source": LaunchConfiguration("map_source").perform(context)},
                {"map_topic": phase2_map_topic},
                {"integrity_topic": "/iap/integrity"},
                {"gnss_scenario_file": LaunchConfiguration("gnss_scenario_file").perform(context)},
                {"range_meas_topic": LaunchConfiguration("phase2_range_meas_topic").perform(context)},
                {"ephem_topic": LaunchConfiguration("phase2_ephem_topic").perform(context)},
                {"glo_ephem_topic": LaunchConfiguration("phase2_glo_ephem_topic").perform(context)},
                {"receiver_lla_topic": LaunchConfiguration("phase2_receiver_lla_topic").perform(context)},
                {"iono_topic": LaunchConfiguration("phase2_iono_topic").perform(context)},
                {"eval_horizon_s": float(LaunchConfiguration("phase2_eval_horizon_s").perform(context))},
                {"eval_dt_s": float(LaunchConfiguration("phase2_eval_dt_s").perform(context))},
                {"max_samples_per_traj": int(LaunchConfiguration("phase2_max_samples_per_traj").perform(context))},
                {"pl_model": LaunchConfiguration("phase2_pl_model").perform(context)},
                {"al_model": LaunchConfiguration("phase2_al_model").perform(context)},
                {"hal_m": float(LaunchConfiguration("phase2_hal_m").perform(context))},
                {"val_m": float(LaunchConfiguration("phase2_val_m").perform(context))},
                {"fallback_pl_m": float(LaunchConfiguration("phase2_fallback_pl_m").perform(context))},
                {"use_pl_grid": _as_bool(LaunchConfiguration("phase2_use_pl_grid").perform(context))},
                {"pl_grid_resolution_m": float(LaunchConfiguration("phase2_pl_grid_resolution_m").perform(context))},
                {"pl_grid_size_x_m": float(LaunchConfiguration("phase2_pl_grid_size_x_m").perform(context))},
                {"pl_grid_size_y_m": float(LaunchConfiguration("phase2_pl_grid_size_y_m").perform(context))},
                {"pl_grid_size_z_m": float(LaunchConfiguration("phase2_pl_grid_size_z_m").perform(context))},
                {"pl_grid_update_hz": float(LaunchConfiguration("phase2_pl_grid_update_hz").perform(context))},
                {"use_lidar_observability": _as_bool(LaunchConfiguration("phase2_use_lidar_observability").perform(context))},
                {"lidar_search_radius_m": float(LaunchConfiguration("phase2_lidar_search_radius_m").perform(context))},
                {"lidar_min_points": int(LaunchConfiguration("phase2_lidar_min_points").perform(context))},
                {"lidar_good_points": int(LaunchConfiguration("phase2_lidar_good_points").perform(context))},
                {"lidar_sigma_m": float(LaunchConfiguration("phase2_lidar_sigma_m").perform(context))},
                {"lidar_info_scale": float(LaunchConfiguration("phase2_lidar_info_scale").perform(context))},
                {"lidar_alpha_min": float(LaunchConfiguration("phase2_lidar_alpha_min").perform(context))},
                {"lidar_alpha_max": float(LaunchConfiguration("phase2_lidar_alpha_max").perform(context))},
                {"lidar_condition_ref": float(LaunchConfiguration("phase2_lidar_condition_ref").perform(context))},
                {"lidar_condition_max": float(LaunchConfiguration("phase2_lidar_condition_max").perform(context))},
                {"lidar_tdop_ref": float(LaunchConfiguration("phase2_lidar_tdop_ref").perform(context))},
                {"lidar_tdop_max": float(LaunchConfiguration("phase2_lidar_tdop_max").perform(context))},
                {"lidar_bias_h_m": float(LaunchConfiguration("phase2_lidar_bias_h_m").perform(context))},
                {"lidar_bias_v_m": float(LaunchConfiguration("phase2_lidar_bias_v_m").perform(context))},
                {"lidar_map_max_points": int(LaunchConfiguration("phase2_lidar_map_max_points").perform(context))},
                {"visibility_hard_occlusion": _as_bool(LaunchConfiguration("phase2_visibility_hard_occlusion").perform(context))},
                {"visibility_occ_range_m": float(LaunchConfiguration("phase2_visibility_occ_range_m").perform(context))},
                {"visibility_occ_l_m": float(LaunchConfiguration("phase2_visibility_occ_l_m").perform(context))},
                {"visibility_ray_start_offset_m": float(LaunchConfiguration("phase2_visibility_ray_start_offset_m").perform(context))},
                {"drone_radius": float(LaunchConfiguration("phase2_drone_radius").perform(context))},
                {"safety_buffer": float(LaunchConfiguration("phase2_safety_buffer").perform(context))},
                {"gamma_h": float(LaunchConfiguration("phase2_gamma_h").perform(context))},
                {"gamma_v": float(LaunchConfiguration("phase2_gamma_v").perform(context))},
                {"pi_cost_weight_h": float(LaunchConfiguration("phase2_pi_cost_weight_h").perform(context))},
                {"pi_cost_weight_v": float(LaunchConfiguration("phase2_pi_cost_weight_v").perform(context))},
                {"pi_cost_marginal_margin_m": float(LaunchConfiguration("phase2_pi_cost_marginal_margin_m").perform(context))},
                {"pi_cost_gradient_step_m": float(LaunchConfiguration("phase2_pi_cost_gradient_step_m").perform(context))},
                {"snapshot_anchor_current_integrity": _as_bool(LaunchConfiguration("phase2_snapshot_anchor_current_integrity").perform(context))},
                {"planner_use_integrity_cost": _as_bool(LaunchConfiguration("planner_use_integrity_cost").perform(context))},
                {"publish_integrity_cost_field": _as_bool(LaunchConfiguration("phase2_publish_integrity_cost_field").perform(context))},
                {"publish_integrity_cost_grid": _as_bool(LaunchConfiguration("phase2_publish_integrity_cost_grid").perform(context))},
                {"integrity_cost_field_topic": LaunchConfiguration("phase2_integrity_cost_field_topic").perform(context)},
                {"z_min": float(LaunchConfiguration("phase2_z_min").perform(context))},
                {"z_max": float(LaunchConfiguration("phase2_z_max").perform(context))},
                {"safe_margin": float(LaunchConfiguration("phase2_safe_margin").perform(context))},
                {"publish_markers": _as_bool(LaunchConfiguration("phase2_publish_markers").perform(context))},
            ],
        ),
        Node(
            package="rviz2",
            executable="rviz2",
            name="demo11_rviz",
            output="screen",
            condition=IfCondition(LaunchConfiguration("start_rviz")),
            arguments=["-d", os.path.join(iap_share, "config", "sim_demo11", "demo11_integrity_corridor.rviz")],
        ),
    ]


def generate_launch_description():
    iap_share = get_package_share_directory("iap")
    return LaunchDescription([
        DeclareLaunchArgument("start_rviz", default_value="true"),
        DeclareLaunchArgument("use_gnss", default_value="true"),
        DeclareLaunchArgument("use_araim", default_value="true"),
        DeclareLaunchArgument("use_iap_odom_for_planner", default_value="false"),
        DeclareLaunchArgument("init_x", default_value="-15.0"),
        DeclareLaunchArgument("init_y", default_value="0.0"),
        DeclareLaunchArgument("init_z", default_value="1.2"),
        DeclareLaunchArgument("goal_x", default_value="10.0"),
        DeclareLaunchArgument("goal_y", default_value="0.0"),
        DeclareLaunchArgument("goal_z", default_value="1.2"),
        DeclareLaunchArgument("point_num", default_value="1"),
        DeclareLaunchArgument("point1_x", default_value="9.5"),
        DeclareLaunchArgument("point1_y", default_value="0.0"),
        DeclareLaunchArgument("point1_z", default_value="1.2"),
        DeclareLaunchArgument("point2_x", default_value="16.0"),
        DeclareLaunchArgument("point2_y", default_value="0.0"),
        DeclareLaunchArgument("point2_z", default_value="1.2"),
        DeclareLaunchArgument("point3_x", default_value="16.0"),
        DeclareLaunchArgument("point3_y", default_value="0.0"),
        DeclareLaunchArgument("point3_z", default_value="1.2"),
        DeclareLaunchArgument("point4_x", default_value="16.0"),
        DeclareLaunchArgument("point4_y", default_value="0.0"),
        DeclareLaunchArgument("point4_z", default_value="1.2"),
        DeclareLaunchArgument("point5_x", default_value="16.0"),
        DeclareLaunchArgument("point5_y", default_value="0.0"),
        DeclareLaunchArgument("point5_z", default_value="1.2"),
        DeclareLaunchArgument("point6_x", default_value="16.0"),
        DeclareLaunchArgument("point6_y", default_value="0.0"),
        DeclareLaunchArgument("point6_z", default_value="1.2"),
        DeclareLaunchArgument("run_duration_s", default_value="90"),
        DeclareLaunchArgument("use_so3_dynamics", default_value="true"),
        DeclareLaunchArgument("planner_use_dynamic", default_value="true"),
        DeclareLaunchArgument("use_dynamic_obstacles", default_value="false"),
        DeclareLaunchArgument("map_source", default_value="global_cloud_direct"),
        DeclareLaunchArgument("allow_truth_alignment", default_value="false"),
        DeclareLaunchArgument("log_phase1", default_value="true"),
        DeclareLaunchArgument("enable_truth_araim_compare", default_value="true"),
        DeclareLaunchArgument("truth_araim_compare_csv_name", default_value="demo11_araim_truth_compare.csv"),
        DeclareLaunchArgument("gnss_ephemeris_source", default_value="rinex"),
        DeclareLaunchArgument("gnss_enabled_constellations", default_value="GPS,BDS,GAL,GLO"),
        DeclareLaunchArgument("gnss_scenario_file", default_value=os.path.join(iap_share, "config", "gnss_sim", "demo7_skymask_nlos.yaml")),
        DeclareLaunchArgument("gnss_rinex_nav_file", default_value="/home/dev/ws_iap/src/LIGO./Data/BRDM00DLR_S_20221870000_01D_MN.rnx"),
        DeclareLaunchArgument("gnss_rinex_ephem_max_age_s", default_value="7200.0"),
        DeclareLaunchArgument("gnss_fallback_to_synthetic_on_rinex_error", default_value="false"),
        DeclareLaunchArgument("gnss_enable_map_occlusion", default_value="true"),
        DeclareLaunchArgument("gnss_enable_skymask", default_value="true"),
        DeclareLaunchArgument("gnss_enable_nlos", default_value="true"),
        DeclareLaunchArgument("gnss_enable_multipath", default_value="true"),
        DeclareLaunchArgument("gnss_enable_fault_injection", default_value="true"),
        DeclareLaunchArgument("gnss_sky_dome_follow_receiver", default_value="false"),
        DeclareLaunchArgument("gnss_sky_dome_center_x", default_value="0.0"),
        DeclareLaunchArgument("gnss_sky_dome_center_y", default_value="0.0"),
        DeclareLaunchArgument("gnss_sky_dome_center_z", default_value="0.0"),
        DeclareLaunchArgument("drone_id", default_value="0"),
        DeclareLaunchArgument("map_size_x", default_value="30.0"),
        DeclareLaunchArgument("map_size_y", default_value="30.0"),
        DeclareLaunchArgument("map_size_z", default_value="3.5"),
        DeclareLaunchArgument("planner_use_integrity_cost", default_value="true"),
        DeclareLaunchArgument("planner_lambda_integrity", default_value="0.001"),
        DeclareLaunchArgument("planner_integrity_field_stale_timeout_s", default_value="1.0"),
        DeclareLaunchArgument("planner_integrity_nearest_radius_m", default_value="1.5"),
        DeclareLaunchArgument("planner_integrity_cost_max", default_value="3000.0"),
        DeclareLaunchArgument("planner_integrity_grad_norm_max", default_value="8.0"),
        DeclareLaunchArgument("corridor_map_resolution_m", default_value="0.1"),
        DeclareLaunchArgument("corridor_map_publish_rate_hz", default_value="2.0"),
        DeclareLaunchArgument("forest_size_x_m", default_value="20.0"),
        DeclareLaunchArgument("forest_size_y_m", default_value="20.0"),
        DeclareLaunchArgument("tree_density_lower_left_per_m2", default_value="0.5"),
        DeclareLaunchArgument("tree_density_lower_right_per_m2", default_value="0.5"),
        DeclareLaunchArgument("tree_density_upper_left_per_m2", default_value="0.5"),
        DeclareLaunchArgument("tree_density_upper_right_per_m2", default_value="0.5"),
        DeclareLaunchArgument("stratified_cell_size_m", default_value="1.0"),
        DeclareLaunchArgument("canopy_density_lower_left", default_value="0.25"),
        DeclareLaunchArgument("canopy_density_lower_right", default_value="0.5"),
        DeclareLaunchArgument("canopy_density_upper_left", default_value="0.5"),
        DeclareLaunchArgument("canopy_density_upper_right", default_value="0.25"),
        DeclareLaunchArgument("canopy_hemisphere_radius_min_m", default_value="0.5"),
        DeclareLaunchArgument("canopy_hemisphere_radius_max_m", default_value="1.5"),
        DeclareLaunchArgument("canopy_leaf_ball_radius_m", default_value="0.22"),
        DeclareLaunchArgument("canopy_ball_spacing_ratio", default_value="1.2"),
        DeclareLaunchArgument("canopy_resolution_m", default_value="0.15"),
        DeclareLaunchArgument("forest_random_seed", default_value="11"),
        DeclareLaunchArgument("trunk_radius_m", default_value="0.14"),
        DeclareLaunchArgument("trunk_min_height_m", default_value="1.5"),
        DeclareLaunchArgument("trunk_max_height_m", default_value="3.0"),
        DeclareLaunchArgument("phase2_eval_horizon_s", default_value="5.0"),
        DeclareLaunchArgument("phase2_eval_dt_s", default_value="0.2"),
        DeclareLaunchArgument("phase2_max_samples_per_traj", default_value="30"),
        DeclareLaunchArgument("phase2_pl_model", default_value="gnss_geometry_araim"),
        DeclareLaunchArgument("phase2_al_model", default_value="fixed_alert_limit"),
        DeclareLaunchArgument("phase2_hal_m", default_value="30.0"),
        DeclareLaunchArgument("phase2_val_m", default_value="60.0"),
        DeclareLaunchArgument("phase2_fallback_pl_m", default_value="20.0"),
        DeclareLaunchArgument("phase2_use_pl_grid", default_value="true"),
        DeclareLaunchArgument("phase2_pl_grid_resolution_m", default_value="1.0"),
        DeclareLaunchArgument("phase2_pl_grid_size_x_m", default_value="18.0"),
        DeclareLaunchArgument("phase2_pl_grid_size_y_m", default_value="18.0"),
        DeclareLaunchArgument("phase2_pl_grid_size_z_m", default_value="5.5"),
        DeclareLaunchArgument("phase2_pl_grid_update_hz", default_value="2.0"),
        DeclareLaunchArgument("phase2_use_lidar_observability", default_value="false"),
        DeclareLaunchArgument("phase2_lidar_search_radius_m", default_value="8.0"),
        DeclareLaunchArgument("phase2_lidar_min_points", default_value="12"),
        DeclareLaunchArgument("phase2_lidar_good_points", default_value="80"),
        DeclareLaunchArgument("phase2_lidar_sigma_m", default_value="0.5"),
        DeclareLaunchArgument("phase2_lidar_info_scale", default_value="1.0"),
        DeclareLaunchArgument("phase2_lidar_alpha_min", default_value="0.02"),
        DeclareLaunchArgument("phase2_lidar_alpha_max", default_value="1.0"),
        DeclareLaunchArgument("phase2_lidar_condition_ref", default_value="30.0"),
        DeclareLaunchArgument("phase2_lidar_condition_max", default_value="1000000.0"),
        DeclareLaunchArgument("phase2_lidar_tdop_ref", default_value="2.0"),
        DeclareLaunchArgument("phase2_lidar_tdop_max", default_value="20.0"),
        DeclareLaunchArgument("phase2_lidar_bias_h_m", default_value="0.0"),
        DeclareLaunchArgument("phase2_lidar_bias_v_m", default_value="0.0"),
        DeclareLaunchArgument("phase2_lidar_map_max_points", default_value="6000"),
        DeclareLaunchArgument("phase2_range_meas_topic", default_value="/ublox_driver/range_meas"),
        DeclareLaunchArgument("phase2_ephem_topic", default_value="/ublox_driver/ephem"),
        DeclareLaunchArgument("phase2_glo_ephem_topic", default_value="/ublox_driver/glo_ephem"),
        DeclareLaunchArgument("phase2_receiver_lla_topic", default_value="/ublox_driver/receiver_lla"),
        DeclareLaunchArgument("phase2_iono_topic", default_value="/ublox_driver/iono_params"),
        DeclareLaunchArgument("phase2_visibility_hard_occlusion", default_value="true"),
        DeclareLaunchArgument("phase2_visibility_occ_range_m", default_value="25.0"),
        DeclareLaunchArgument("phase2_visibility_occ_l_m", default_value="8.0"),
        DeclareLaunchArgument("phase2_visibility_ray_start_offset_m", default_value="1.0"),
        DeclareLaunchArgument("phase2_drone_radius", default_value="0.35"),
        DeclareLaunchArgument("phase2_safety_buffer", default_value="0.20"),
        DeclareLaunchArgument("phase2_gamma_h", default_value="0.8"),
        DeclareLaunchArgument("phase2_gamma_v", default_value="0.8"),
        DeclareLaunchArgument("phase2_pi_cost_weight_h", default_value="1.0"),
        DeclareLaunchArgument("phase2_pi_cost_weight_v", default_value="0.0"),
        DeclareLaunchArgument("phase2_pi_cost_marginal_margin_m", default_value="4.0"),
        DeclareLaunchArgument("phase2_pi_cost_gradient_step_m", default_value="0.5"),
        DeclareLaunchArgument("phase2_snapshot_anchor_current_integrity", default_value="true"),
        DeclareLaunchArgument("phase2_publish_integrity_cost_field", default_value="true"),
        DeclareLaunchArgument("phase2_publish_integrity_cost_grid", default_value="true"),
        DeclareLaunchArgument("phase2_integrity_cost_field_topic", default_value="/iap/integrity_cost_field"),
        DeclareLaunchArgument("phase2_z_min", default_value="0.0"),
        DeclareLaunchArgument("phase2_z_max", default_value="5.5"),
        DeclareLaunchArgument("phase2_safe_margin", default_value="0.0"),
        DeclareLaunchArgument("phase2_publish_markers", default_value="true"),
        OpaqueFunction(function=_launch_setup),
    ])
