#!/usr/bin/env python3
"""
Run-scoped log analyzer for the current IAP logging layout.

Default input:
  src/iap/log/latest

Supported layout:
  runtime/*.log
  profiling/iap_timing.csv
  export/iap_icp.csv
  export/iap_gnss_factor_debug.csv
  export/iap_araim.csv
  export/traj_with_gnss.csv
  export/dump/*
  metadata/run_info.json
  metadata/config/*.json

The old CT/frontend-only artifacts were intentionally removed from this
analyzer. This script reports only artifacts that exist in the new run-scoped
logging contract.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, median
from typing import Any


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUN = PACKAGE_ROOT / "log" / "latest"

RUNTIME_LOG_RE = re.compile(
    r"^\[(?P<ts>[^\]]+)\]\s+\[(?P<logger>[^\]]+)\]\s+\[(?P<level>[^\]]+)\]\s+(?P<message>.*)$"
)
NUMBER_RE = re.compile(r"\b\d+(?:\.\d+)?\b")


@dataclass
class ArtifactStatus:
    name: str
    rel_path: str
    status: str
    reason: str
    rows: int | None = None
    size_bytes: int = 0
    note: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze one current-format IAP run directory.")
    parser.add_argument("--run", default=str(DEFAULT_RUN), help=f"Run directory to analyze (default: {DEFAULT_RUN})")
    parser.add_argument("--out", default="", help="Output analysis directory (default: <run>/analysis)")
    parser.add_argument("--no-plots", action="store_true", help="Skip plots generated by ana_log.py")
    parser.add_argument("--skip-external-tools", action="store_true", help="Do not invoke ICP/GNSS/ARAIM plot scripts")
    parser.add_argument("--strict", action="store_true", help="Exit non-zero if runtime errors or enabled current artifacts are missing")
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def resolve_run_dir(run_arg: str) -> Path:
    candidate = Path(run_arg)
    if not candidate.is_absolute() and not candidate.exists():
        candidate = PACKAGE_ROOT / run_arg
    candidate = candidate.resolve()
    if not candidate.exists():
        raise FileNotFoundError(f"Run path does not exist: {candidate}")
    if not candidate.is_dir():
        raise NotADirectoryError(f"Run path is not a directory: {candidate}")
    return candidate


def strip_json_comments(text: str) -> str:
    result: list[str] = []
    i = 0
    in_string = False
    quote = ""
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""
        if in_string:
            result.append(ch)
            if ch == "\\" and i + 1 < len(text):
                result.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                in_string = False
            i += 1
            continue
        if ch in {"'", '"'}:
            in_string = True
            quote = ch
            result.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "/":
            i += 2
            while i < len(text) and text[i] != "\n":
                i += 1
            continue
        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < len(text) and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        result.append(ch)
        i += 1
    return "".join(result)


def load_jsonish(path: Path) -> Any:
    if not path.exists() or path.stat().st_size == 0:
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.strip():
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return json.loads(strip_json_comments(text))


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open("r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            return []
        return [dict(row) for row in reader]


def to_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    if text == "":
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    if not math.isfinite(number):
        return None
    return number


def numeric_values(rows: list[dict[str, str]], column: str) -> list[float]:
    values = []
    for row in rows:
        value = to_float(row.get(column))
        if value is not None:
            values.append(value)
    return values


def first_value(row: dict[str, str], columns: list[str]) -> Any:
    for column in columns:
        value = row.get(column)
        if value not in (None, ""):
            return value
    return None


def first_number(row: dict[str, str], columns: list[str]) -> float | None:
    return to_float(first_value(row, columns))


def numeric_values_any(rows: list[dict[str, str]], columns: list[str]) -> list[float]:
    values = []
    for row in rows:
        value = first_number(row, columns)
        if value is not None:
            values.append(value)
    return values


def boolish(value: Any) -> bool | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "on", "y"}:
        return True
    if text in {"0", "false", "no", "off", "n"}:
        return False
    return None


def quantile(values: list[float], q: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return float(ordered[0])
    pos = (len(ordered) - 1) * q
    lower = math.floor(pos)
    upper = math.ceil(pos)
    if lower == upper:
        return float(ordered[lower])
    weight = pos - lower
    return float(ordered[lower] * (1.0 - weight) + ordered[upper] * weight)


def stats(values: list[float]) -> dict[str, float | int]:
    if not values:
        return {"count": 0, "mean": 0.0, "p50": 0.0, "p95": 0.0, "p99": 0.0, "max": 0.0, "min": 0.0}
    return {
        "count": len(values),
        "mean": float(mean(values)),
        "p50": float(median(values)),
        "p95": quantile(values, 0.95),
        "p99": quantile(values, 0.99),
        "max": float(max(values)),
        "min": float(min(values)),
    }


def rms(values: list[float]) -> float:
    if not values:
        return 0.0
    return math.sqrt(sum(v * v for v in values) / len(values))


def human_size(size_bytes: int) -> str:
    value = float(size_bytes)
    for suffix in ["B", "KiB", "MiB", "GiB"]:
        if value < 1024.0 or suffix == "GiB":
            return f"{value:.1f} {suffix}" if suffix != "B" else f"{int(value)} B"
        value /= 1024.0
    return f"{size_bytes} B"


def normalize_message(message: str) -> str:
    msg = NUMBER_RE.sub("<n>", message)
    msg = re.sub(r"/[A-Za-z0-9_./-]+", "<path>", msg)
    return msg[:200]


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    def fmt(value: Any) -> str:
        text = str(value)
        return text.replace("\n", "<br>").replace("|", "\\|")

    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(fmt(item) for item in row) + " |")
    return "\n".join(lines)


def first_existing(run_dir: Path, candidates: list[str]) -> tuple[Path, str] | tuple[None, str]:
    for rel_path in candidates:
        path = run_dir / rel_path
        if path.exists():
            return path, rel_path
    return None, candidates[0]


def artifact_paths(run_dir: Path) -> dict[str, tuple[Path | None, str, list[str]]]:
    aliases = {
        "run_info": ["metadata/run_info.json"],
        "timing": ["profiling/iap_timing.csv", "profiling/pipeline_timing.csv"],
        "icp": ["export/iap_icp.csv", "export/icp_quality.csv"],
        "gnss_factor_debug": ["export/iap_gnss_factor_debug.csv", "export/gnss_factor_debug.csv"],
        "araim": ["export/iap_araim.csv", "export/araim.csv"],
        "trajectory": ["export/traj_with_gnss.csv", "export/integrity_trajectory.csv"],
    }
    result = {}
    for name, candidates in aliases.items():
        path, rel = first_existing(run_dir, candidates)
        result[name] = (path, rel, candidates)
    return result


def config_enabled(configs: dict[str, Any], artifact_name: str) -> bool | None:
    config_json = configs.get("config")
    config_gnss = configs.get("config_gnss")
    config_odom = (
        configs.get("config_odometry")
        or configs.get("config_odometry_gpu")
        or configs.get("config_odometry_cpu")
    )
    config_ros = configs.get("config_ros")

    if artifact_name == "timing":
        return nested_bool(config_json, ["global", "enable_timing_csv"])
    if artifact_name == "icp":
        return nested_bool(config_odom, ["odometry_estimation", "enable_icp_csv"])
    if artifact_name == "gnss_factor_debug":
        return nested_bool(config_gnss, ["gnss", "enable_debug_csv"])
    if artifact_name == "araim":
        return nested_bool(config_gnss, ["integrity", "enable_araim_csv"])
    if artifact_name == "trajectory":
        return nested_bool(config_gnss, ["integrity", "enable_traj_csv"])
    if artifact_name == "dump":
        local_mapping = nested_bool(config_ros, ["glim_ros", "enable_local_mapping"])
        global_mapping = nested_bool(config_ros, ["glim_ros", "enable_global_mapping"])
        if local_mapping is None and global_mapping is None:
            return None
        return bool(local_mapping or global_mapping)
    return None


def nested_get(obj: Any, path: list[str]) -> Any:
    cur = obj
    for key in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
    return cur


def nested_bool(obj: Any, path: list[str]) -> bool | None:
    value = nested_get(obj, path)
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        low = value.strip().lower()
        if low in {"1", "true", "yes", "on"}:
            return True
        if low in {"0", "false", "no", "off"}:
            return False
    return None


def load_metadata(run_dir: Path) -> dict[str, Any]:
    metadata_dir = run_dir / "metadata"
    config_dir = metadata_dir / "config"
    run_info = load_jsonish(metadata_dir / "run_info.json") or {}
    configs: dict[str, Any] = {}
    if config_dir.exists():
        for config_file in sorted(config_dir.glob("*.json")):
            configs[config_file.stem] = load_jsonish(config_file)

    legacy: dict[str, Any] = {}
    for name in ["config_snapshot.json", "git_rev.txt", "build_info.txt"]:
        path = metadata_dir / name
        if path.exists():
            legacy[name] = path.read_text(encoding="utf-8", errors="replace").strip()

    return {"run_info": run_info, "configs": configs, "legacy": legacy}


def parse_runtime_logs(run_dir: Path) -> dict[str, Any]:
    runtime_dir = run_dir / "runtime"
    summary: dict[str, Any] = {
        "files": [],
        "total_lines": 0,
        "level_counts": Counter(),
        "logger_counts": Counter(),
        "issues": [],
        "pattern_counts": Counter(),
        "loaded_modules": [],
        "shutdown_messages": [],
        "save_messages": [],
    }
    if not runtime_dir.exists():
        return summary

    for log_path in sorted(runtime_dir.glob("*.log")):
        file_summary = {"file": log_path.name, "lines": 0, "level_counts": Counter()}
        for line_no, raw in enumerate(log_path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
            file_summary["lines"] += 1
            summary["total_lines"] += 1
            match = RUNTIME_LOG_RE.match(raw)
            if not match:
                continue
            level = match.group("level").lower()
            logger = match.group("logger")
            message = match.group("message")
            file_summary["level_counts"][level] += 1
            summary["level_counts"][level] += 1
            summary["logger_counts"][logger] += 1
            if "load lib" in message:
                summary["loaded_modules"].append(message.replace("load ", "", 1))
            if "waiting for" in message or "shutdown" in message.lower():
                summary["shutdown_messages"].append(message)
            if "saving" in message or "serializing" in message or "dump" in message:
                summary["save_messages"].append(message)
            if level in {"warn", "warning", "error", "critical"}:
                issue = {"file": log_path.name, "line": line_no, "level": level, "message": message}
                summary["issues"].append(issue)
                summary["pattern_counts"][normalize_message(message)] += 1
        summary["files"].append(file_summary)

    summary["top_patterns"] = summary["pattern_counts"].most_common(10)
    return summary


def scan_artifacts(run_dir: Path, metadata: dict[str, Any]) -> list[ArtifactStatus]:
    configs = metadata.get("configs", {})
    paths = artifact_paths(run_dir)
    artifacts: list[ArtifactStatus] = []

    for name, (path, rel_path, candidates) in paths.items():
        exists = path is not None and path.exists()
        size = path.stat().st_size if exists and path is not None else 0
        rows: int | None = None
        if exists and path is not None and path.suffix == ".csv":
            rows = len(load_csv_rows(path))

        enabled = config_enabled(configs, name)
        if exists and size > 0 and (rows is None or rows > 0):
            status = "found"
            reason = "found_with_data"
        elif exists:
            status = "empty"
            reason = "empty_file"
        elif enabled is False:
            status = "disabled"
            reason = "expected_missing_by_config"
        elif enabled is True:
            status = "expected_missing"
            reason = "enabled_but_missing"
        else:
            status = "missing"
            reason = "availability_unclear"

        note = ""
        if len(candidates) > 1:
            note = "aliases: " + ", ".join(candidates)
        artifacts.append(ArtifactStatus(name, rel_path, status, reason, rows, size, note))

    config_files = sorted((run_dir / "metadata" / "config").glob("*.json"))
    artifacts.append(
        ArtifactStatus(
            "config_snapshot",
            "metadata/config/*.json",
            "found" if config_files else "missing",
            "found_with_data" if config_files else "missing_config_snapshot",
            rows=len(config_files),
            size_bytes=sum(path.stat().st_size for path in config_files),
            note=f"{len(config_files)} config files",
        )
    )

    runtime_files = sorted((run_dir / "runtime").glob("*.log"))
    artifacts.append(
        ArtifactStatus(
            "runtime_logs",
            "runtime/*.log",
            "found" if runtime_files else "missing",
            "found_with_data" if runtime_files else "missing_runtime_logs",
            rows=len(runtime_files),
            size_bytes=sum(path.stat().st_size for path in runtime_files),
            note=f"{len(runtime_files)} log files",
        )
    )

    dump_dir = run_dir / "export" / "dump"
    dump_files = [path for path in dump_dir.rglob("*") if path.is_file()] if dump_dir.exists() else []
    dump_enabled = config_enabled(configs, "dump")
    if dump_files:
        status, reason = "found", "found_with_data"
    elif dump_enabled is False:
        status, reason = "disabled", "expected_missing_by_config"
    elif dump_enabled is True:
        status, reason = "expected_missing", "enabled_but_missing"
    else:
        status, reason = "missing", "availability_unclear"
    artifacts.append(
        ArtifactStatus(
            "dump_export",
            "export/dump/*",
            status,
            reason,
            rows=len(dump_files),
            size_bytes=sum(path.stat().st_size for path in dump_files),
            note=f"{len(dump_files)} files",
        )
    )
    return artifacts


def analyze_timing(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"available": False}
    by_module: dict[str, list[float]] = defaultdict(list)
    for row in rows:
        module = row.get("module", "").strip() or "unknown"
        elapsed = first_number(row, ["elapsed_ms", "duration_ms", "time_ms", "ms", "elapsed", "duration"])
        if elapsed is not None:
            by_module[module].append(elapsed)
    module_stats = []
    for module, values in by_module.items():
        item = {"module": module, **stats(values)}
        module_stats.append(item)
    module_stats.sort(key=lambda item: float(item["mean"]), reverse=True)
    return {"available": True, "row_count": len(rows), "module_stats": module_stats}


def analyze_icp(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"available": False}
    drop_flags = []
    for row in rows:
        drop_value = first_value(row, ["drop_flag", "is_degenerate", "degenerate"])
        drop_flags.append(boolish(drop_value) is True)
    return {
        "available": True,
        "frame_count": len(rows),
        "degenerate_count": sum(1 for value in drop_flags if value),
        "degenerate_ratio": sum(1 for value in drop_flags if value) / max(len(rows), 1),
        "rmse": stats(numeric_values(rows, "rmse")),
        "inlier_fraction": stats(numeric_values(rows, "inlier_fraction")),
        "condition_number": stats(numeric_values(rows, "condition_number")),
        "gamma_lidar": stats(numeric_values(rows, "gamma_lidar")),
    }


def analyze_gnss(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"available": False}
    factor_counts = Counter((first_value(row, ["factor_type", "type"]) or "unknown").strip() for row in rows)
    sat_labels = {
        f"{row.get('constellation', '').strip()}{str(first_value(row, ['sat_id', 'sat']) or '').strip()}"
        for row in rows
        if first_value(row, ["sat_id", "sat"])
    }
    constellations = {row.get("constellation", "").strip() for row in rows if row.get("constellation")}
    residual_by_type: dict[str, list[float]] = defaultdict(list)
    norm_by_type: dict[str, list[float]] = defaultdict(list)
    for row in rows:
        ftype = (first_value(row, ["factor_type", "type"]) or "unknown").strip()
        residual = to_float(row.get("residual"))
        normalized = to_float(row.get("normalized_residual"))
        if residual is not None:
            residual_by_type[ftype].append(residual)
        if normalized is not None:
            norm_by_type[ftype].append(normalized)

    type_stats = {}
    for ftype in sorted(set(residual_by_type) | set(norm_by_type)):
        type_stats[ftype] = {
            "residual_rms": rms(residual_by_type.get(ftype, [])),
            "normalized_residual_rms": rms(norm_by_type.get(ftype, [])),
            "residual": stats(residual_by_type.get(ftype, [])),
            "normalized_residual": stats(norm_by_type.get(ftype, [])),
        }

    return {
        "available": True,
        "row_count": len(rows),
        "factor_counts": dict(factor_counts),
        "satellite_count": len(sat_labels),
        "constellation_count": len(constellations),
        "constellations": sorted(constellations),
        "type_stats": type_stats,
    }


def analyze_araim(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"available": False}
    epochs = [row for row in rows if row.get("row_type") == "epoch"]
    worst_hyp = [row for row in rows if row.get("row_type") == "worst_hyp"]
    states = Counter(row.get("state", "unknown") for row in epochs)
    unsafe_count = states.get("UNSAFE", 0)
    return {
        "available": True,
        "row_count": len(rows),
        "epoch_count": len(epochs),
        "worst_hyp_count": len(worst_hyp),
        "state_counts": dict(states),
        "unsafe_ratio": unsafe_count / max(len(epochs), 1),
        "HPL": stats(numeric_values(epochs, "HPL")),
        "VPL": stats(numeric_values(epochs, "VPL")),
        "HAL": stats(numeric_values(epochs, "HAL")),
        "VAL": stats(numeric_values(epochs, "VAL")),
        "IM": stats(numeric_values(epochs, "IM")),
        "n_hyp": stats(numeric_values(epochs, "n_hyp")),
        "n_det": stats(numeric_values(epochs, "n_det")),
    }


def analyze_trajectory(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"available": False}
    stamps = numeric_values_any(rows, ["stamp", "timestamp", "time"])
    xs = numeric_values(rows, "x")
    ys = numeric_values(rows, "y")
    zs = numeric_values(rows, "z")
    span_s = max(stamps) - min(stamps) if len(stamps) >= 2 else 0.0
    path_length = 0.0
    points = []
    for row in rows:
        x, y, z = to_float(row.get("x")), to_float(row.get("y")), to_float(row.get("z"))
        if x is not None and y is not None and z is not None:
            points.append((x, y, z))
    for prev, cur in zip(points, points[1:]):
        path_length += math.sqrt(sum((cur[i] - prev[i]) ** 2 for i in range(3)))
    return {
        "available": True,
        "row_count": len(rows),
        "span_s": span_s,
        "path_length_m": path_length,
        "x": stats(xs),
        "y": stats(ys),
        "z": stats(zs),
    }


def analyze_dump(run_dir: Path) -> dict[str, Any]:
    dump_dir = run_dir / "export" / "dump"
    if not dump_dir.exists():
        return {"available": False}
    files = [path for path in dump_dir.rglob("*") if path.is_file()]
    submap_dirs = [path for path in dump_dir.iterdir() if path.is_dir() and path.name.isdigit()]
    required = ["graph.bin", "values.bin", "graph.txt", "traj_imu.txt", "traj_lidar.txt", "odom_imu.txt", "odom_lidar.txt"]
    return {
        "available": True,
        "file_count": len(files),
        "submap_count": len(submap_dirs),
        "total_size_bytes": sum(path.stat().st_size for path in files),
        "total_size": human_size(sum(path.stat().st_size for path in files)),
        "required_files": {name: (dump_dir / name).exists() for name in required},
    }


def import_matplotlib() -> tuple[Any, str]:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        return plt, ""
    except Exception as exc:  # pragma: no cover - depends on local environment
        return None, f"matplotlib unavailable: {exc}"


def maybe_generate_timing_plot(timing_analysis: dict[str, Any], out_dir: Path, no_plots: bool) -> list[str]:
    if no_plots or not timing_analysis.get("available"):
        return []
    plt, error = import_matplotlib()
    if plt is None:
        return [error]
    ensure_dir(out_dir)
    modules = [item["module"] for item in timing_analysis["module_stats"]]
    means = [item["mean"] for item in timing_analysis["module_stats"]]
    p95s = [item["p95"] for item in timing_analysis["module_stats"]]
    fig, ax = plt.subplots(figsize=(12, 5))
    xs = range(len(modules))
    ax.bar([x - 0.2 for x in xs], means, width=0.4, label="mean_ms")
    ax.bar([x + 0.2 for x in xs], p95s, width=0.4, label="p95_ms")
    ax.set_xticks(list(xs))
    ax.set_xticklabels(modules, rotation=30, ha="right")
    ax.set_ylabel("elapsed_ms")
    ax.set_title("IAP Module Timing")
    ax.grid(True, alpha=0.3, axis="y")
    ax.legend()
    fig.tight_layout()
    path = out_dir / "module_timing_summary.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return [str(path)]


def run_external_plot(script: Path, args: list[str]) -> dict[str, Any]:
    proc = subprocess.run([sys.executable, str(script), *args], capture_output=True, text=True, check=False)
    return {
        "script": script.name,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def integrate_external_plots(run_dir: Path, rows_by_name: dict[str, list[dict[str, str]]], out_dir: Path) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    ensure_dir(out_dir)
    paths = artifact_paths(run_dir)
    icp_path = paths["icp"][0]
    timing_path = paths["timing"][0]
    if icp_path and timing_path and rows_by_name.get("icp") and rows_by_name.get("timing"):
        icp_out = out_dir / "icp"
        ensure_dir(icp_out)
        results.append(run_external_plot(PACKAGE_ROOT / "tools" / "plot_icp_timing.py", [str(icp_path), str(timing_path), str(icp_out)]))
    gnss_path = paths["gnss_factor_debug"][0]
    if gnss_path and rows_by_name.get("gnss_factor_debug"):
        gnss_out = out_dir / "gnss_factor_debug"
        ensure_dir(gnss_out)
        results.append(run_external_plot(PACKAGE_ROOT / "tools" / "plot_gnss_factor_debug.py", ["--csv", str(gnss_path), "--out", str(gnss_out)]))
    araim_path = paths["araim"][0]
    if araim_path and rows_by_name.get("araim"):
        araim_out = out_dir / "araim"
        ensure_dir(araim_out)
        results.append(run_external_plot(PACKAGE_ROOT / "tools" / "plot_araim_timeline.py", [str(araim_path), str(araim_out)]))
    return results


def render_report(
    run_dir: Path,
    metadata: dict[str, Any],
    artifacts: list[ArtifactStatus],
    runtime: dict[str, Any],
    analyses: dict[str, Any],
    generated_plots: list[str],
    external_results: list[dict[str, Any]],
) -> str:
    run_info = metadata.get("run_info", {})
    lines: list[str] = ["# IAP Run Analysis", ""]

    lines.append("## Run Summary")
    lines.append("")
    lines.append(md_table(
        ["Key", "Value"],
        [
            ["run_dir", run_dir],
            ["process_name", run_info.get("process_name", "")],
            ["start_timestamp", run_info.get("start_timestamp", "")],
            ["git_commit", run_info.get("git_commit", "")],
            ["build_type", run_info.get("build_type", "")],
            ["config_dir", run_info.get("config_dir", "")],
            ["source_root", run_info.get("source_root", "")],
        ],
    ))
    lines.append("")

    lines.append("## Artifact Coverage")
    lines.append("")
    lines.append(md_table(
        ["Artifact", "Path", "Status", "Rows/Files", "Size", "Reason", "Note"],
        [[a.name, a.rel_path, a.status, "" if a.rows is None else a.rows, human_size(a.size_bytes), a.reason, a.note] for a in artifacts],
    ))
    lines.append("")

    lines.append("## Runtime Warnings/Errors")
    lines.append("")
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["runtime log files", len(runtime.get("files", []))],
            ["total lines", runtime.get("total_lines", 0)],
            ["level counts", dict(runtime.get("level_counts", {}))],
            ["loaded modules", ", ".join(runtime.get("loaded_modules", []))],
        ],
    ))
    issues = runtime.get("issues", [])
    if issues:
        lines.append("")
        lines.append(md_table(
            ["File", "Line", "Level", "Message"],
            [[item["file"], item["line"], item["level"], item["message"][:240]] for item in issues[:30]],
        ))
    if runtime.get("top_patterns"):
        lines.append("")
        lines.append(md_table(
            ["Count", "Pattern"],
            [[count, pattern] for pattern, count in runtime["top_patterns"]],
        ))
    lines.append("")

    append_timing_section(lines, analyses.get("timing", {}))
    append_icp_section(lines, analyses.get("icp", {}))
    append_gnss_section(lines, analyses.get("gnss_factor_debug", {}))
    append_araim_section(lines, analyses.get("araim", {}))
    append_trajectory_section(lines, analyses.get("trajectory", {}))
    append_dump_section(lines, analyses.get("dump", {}))

    lines.append("## Generated Plots")
    lines.append("")
    lines.append("\n".join(f"- `{item}`" for item in generated_plots) if generated_plots else "No plots generated.")
    lines.append("")

    lines.append("## External Plot Integrations")
    lines.append("")
    if external_results:
        lines.append(md_table(
            ["Script", "Return Code", "Stdout", "Stderr"],
            [[item["script"], item["returncode"], item["stdout"][:160], item["stderr"][:240]] for item in external_results],
        ))
    else:
        lines.append("No external analysis scripts were invoked.")
    lines.append("")
    return "\n".join(lines)


def append_timing_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## Module Timing")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`profiling/iap_timing.csv` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Module", "Count", "Mean ms", "P50 ms", "P95 ms", "P99 ms", "Max ms"],
        [[item["module"], item["count"], f"{item['mean']:.3f}", f"{item['p50']:.3f}", f"{item['p95']:.3f}", f"{item['p99']:.3f}", f"{item['max']:.3f}"] for item in analysis["module_stats"]],
    ))
    lines.append("")


def append_icp_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## ICP Quality")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`export/iap_icp.csv` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["frame_count", analysis["frame_count"]],
            ["degenerate_count", analysis["degenerate_count"]],
            ["degenerate_ratio", f"{analysis['degenerate_ratio']:.3f}"],
            ["rmse mean/p95/max", format_triplet(analysis["rmse"])],
            ["inlier_fraction mean/p95/min", format_triplet(analysis["inlier_fraction"], min_instead=True)],
            ["condition_number mean/p95/max", format_triplet(analysis["condition_number"])],
            ["gamma_lidar mean/p95/max", format_triplet(analysis["gamma_lidar"])],
        ],
    ))
    lines.append("")


def append_gnss_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## GNSS Factor Debug")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`export/iap_gnss_factor_debug.csv` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["row_count", analysis["row_count"]],
            ["factor_counts", analysis["factor_counts"]],
            ["satellite_count", analysis["satellite_count"]],
            ["constellations", ", ".join(analysis["constellations"])],
        ],
    ))
    rows = []
    for ftype, item in analysis["type_stats"].items():
        rows.append([
            ftype,
            f"{item['residual_rms']:.3f}",
            f"{item['normalized_residual_rms']:.3f}",
            format_triplet(item["residual"]),
            format_triplet(item["normalized_residual"]),
        ])
    lines.append("")
    lines.append(md_table(["Type", "Residual RMS", "Norm Residual RMS", "Residual mean/p95/max", "Norm mean/p95/max"], rows))
    lines.append("")


def append_araim_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## ARAIM Timeline Summary")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`export/iap_araim.csv` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["epoch_count", analysis["epoch_count"]],
            ["worst_hyp_count", analysis["worst_hyp_count"]],
            ["state_counts", analysis["state_counts"]],
            ["unsafe_ratio", f"{analysis['unsafe_ratio']:.3f}"],
            ["HPL mean/p95/max", format_triplet(analysis["HPL"])],
            ["VPL mean/p95/max", format_triplet(analysis["VPL"])],
            ["HAL mean/p95/max", format_triplet(analysis["HAL"])],
            ["VAL mean/p95/max", format_triplet(analysis["VAL"])],
            ["IM mean/p95/min", format_triplet(analysis["IM"], min_instead=True)],
            ["n_hyp mean/p95/max", format_triplet(analysis["n_hyp"])],
            ["n_det mean/p95/max", format_triplet(analysis["n_det"])],
        ],
    ))
    lines.append("")


def append_trajectory_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## Trajectory Export Summary")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`export/traj_with_gnss.csv` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["row_count", analysis["row_count"]],
            ["span_s", f"{analysis['span_s']:.3f}"],
            ["path_length_m", f"{analysis['path_length_m']:.3f}"],
            ["x mean/p95/max", format_triplet(analysis["x"])],
            ["y mean/p95/max", format_triplet(analysis["y"])],
            ["z mean/p95/max", format_triplet(analysis["z"])],
        ],
    ))
    lines.append("")


def append_dump_section(lines: list[str], analysis: dict[str, Any]) -> None:
    lines.append("## Dump Export Summary")
    lines.append("")
    if not analysis.get("available"):
        lines.append("`export/dump` was not available.")
        lines.append("")
        return
    lines.append(md_table(
        ["Metric", "Value"],
        [
            ["file_count", analysis["file_count"]],
            ["submap_count", analysis["submap_count"]],
            ["total_size", analysis["total_size"]],
            ["required_files", analysis["required_files"]],
        ],
    ))
    lines.append("")


def format_triplet(item: dict[str, Any], min_instead: bool = False) -> str:
    last_key = "min" if min_instead else "max"
    return f"{item.get('mean', 0.0):.3f} / {item.get('p95', 0.0):.3f} / {item.get(last_key, 0.0):.3f}"


def build_json_payload(
    run_dir: Path,
    metadata: dict[str, Any],
    artifacts: list[ArtifactStatus],
    runtime: dict[str, Any],
    analyses: dict[str, Any],
    generated_plots: list[str],
    external_results: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "run_dir": str(run_dir),
        "metadata": metadata,
        "artifact_statuses": [artifact.__dict__ for artifact in artifacts],
        "runtime_summary": {
            "total_lines": runtime.get("total_lines", 0),
            "level_counts": dict(runtime.get("level_counts", {})),
            "logger_counts": dict(runtime.get("logger_counts", {})),
            "loaded_modules": runtime.get("loaded_modules", []),
            "shutdown_messages": runtime.get("shutdown_messages", []),
            "save_messages": runtime.get("save_messages", []),
            "issues": runtime.get("issues", []),
            "top_patterns": runtime.get("top_patterns", []),
        },
        "analyses": analyses,
        "generated_plots": generated_plots,
        "external_results": external_results,
    }


def main() -> int:
    args = parse_args()
    run_dir = resolve_run_dir(args.run)
    out_dir = Path(args.out).resolve() if args.out else run_dir / "analysis"
    figs_dir = out_dir / "figs"
    ensure_dir(out_dir)
    ensure_dir(figs_dir)

    metadata = load_metadata(run_dir)
    runtime = parse_runtime_logs(run_dir)
    artifacts = scan_artifacts(run_dir, metadata)
    paths = artifact_paths(run_dir)
    rows_by_name = {
        name: load_csv_rows(path)
        for name, (path, _rel, _aliases) in paths.items()
        if path is not None and path.suffix == ".csv"
    }

    analyses = {
        "timing": analyze_timing(rows_by_name.get("timing", [])),
        "icp": analyze_icp(rows_by_name.get("icp", [])),
        "gnss_factor_debug": analyze_gnss(rows_by_name.get("gnss_factor_debug", [])),
        "araim": analyze_araim(rows_by_name.get("araim", [])),
        "trajectory": analyze_trajectory(rows_by_name.get("trajectory", [])),
        "dump": analyze_dump(run_dir),
    }

    generated_plots = maybe_generate_timing_plot(analyses["timing"], figs_dir, args.no_plots)
    external_results: list[dict[str, Any]] = []
    if not args.skip_external_tools:
        external_results = integrate_external_plots(run_dir, rows_by_name, figs_dir / "external")

    report_md = render_report(run_dir, metadata, artifacts, runtime, analyses, generated_plots, external_results)
    report_md_path = out_dir / "report.md"
    report_json_path = out_dir / "report.json"
    report_md_path.write_text(report_md, encoding="utf-8")
    report_json_path.write_text(
        json.dumps(
            build_json_payload(run_dir, metadata, artifacts, runtime, analyses, generated_plots, external_results),
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"Analyzed run: {run_dir}")
    print(f"Markdown report: {report_md_path}")
    print(f"JSON report    : {report_json_path}")
    print(f"Figures dir     : {figs_dir}")

    if args.strict:
        has_runtime_error = any(issue["level"] in {"error", "critical"} for issue in runtime.get("issues", []))
        missing_enabled = any(artifact.status == "expected_missing" for artifact in artifacts)
        if has_runtime_error or missing_enabled:
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
